name: push_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
